name: Run BugBug Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  bugbug-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installa BugBug CLI
        run: npm install -g bugbug-cli

      - name: Esegui test BugBug
        run: bugbug run
        env:
          BUGBUG_API_KEY: ${{ secrets.bugbug_bd31005a713c5c08f63d7b212003209b38ef8b35 }}
