name: Test sito web

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run BugBug test
        uses: bugbug-io/bugbug-github-action@v1
        with:
          apiToken: ${{ secrets.bugbug_bd31005a713c5c08f63d7b212003209b38ef8b35 }}
          testId: 4526ed39-eccc-4c6e-8de1-ac895c28c1f6
